### ISSUE TITLE
Request: Compatibility with PCA 9634

### ISSUE THREAD

**Issue by Luxovious** [RobTillaart/PCA9635#12]
Hi Rob Tillaart,
Thank you for such a wonderful library. Unfortunatly, I'm working with the smaller brother (8 LEDs, 8 bit) of the same chip. It is called PCA9634 and I'm not sure if your library can be adapted for that chip. Since I'm an absolute noob, I was wondering if you would find the time and take a look at it, if this would be feasible.

I have the datasheet to this chip attached: [Datasheet PCA9634.pdf](https://github.com/RobTillaart/PCA9635/files/7802580/Datasheet.PCA9634.pdf)

Thank you in advance!
Lux

**Comment by RobTillaart** [comment]
Hi,
I will have a quick look at the datasheet

**Comment by RobTillaart** [comment]
Check paragraph 7.3 of both datasheets, the register mapping differs, so this library cannot be used for the **PCA9634**

[PCA9635.pdf](https://github.com/RobTillaart/PCA9635/files/7802700/PCA9635.pdf)

What is possible is to create a library with the same interface and adjusted register mapping. 
As I have no hardware you should do the testing.

**Comment by RobTillaart** [comment]
A quick search 
There already exist 
- https://github.com/mmojana/pca9634-arduino-library
- https://github.com/NickvanTholen/pca9634-lib/

Don't know if these would fit your needs.

Note the Nick van Tholen library has examples and has a more elaborated readme. I would check that one first.

**Comment by RobTillaart** [comment]
If you want a library that is has similar API as mine, I need to write it (takes time estimate 10-15 hours )
And as I do not have the HW I cannot test it, could you do that?

**Comment by Luxovious** [comment]
I'm happy to test.
I have tried to use the mmojana lib, however it does not work with my breakout board. I have checked my hardware multiple times and I'm pretty sure it works. To make sure I designed a new board this morning and I'm now waiting for the arrival from china.

I suggest, that I test the lib from Nick van Tholen first (somehow I must have missed that one). Therefore, you don't have to spend too much work reinventing the wheel. I'll get back with the results (bad or good), as soon as I have them.

Thank you VERY much, for replying to my request and keeping your library up to date. Guys like you really help noobs like me :-)

**Comment by Luxovious** [comment]
As it seems I must have killed my chip somehow. None of the samples work. I have a few more chips and empty boards, I'll go and solder a bit :-D

**Comment by RobTillaart** [comment]
> As it seems I must have killed my chip somehow. None of the samples work. I

that hurts ...

FYI I started with a library here - https://github.com/RobTillaart/PCA9634
stripped a copy of the pca9635, just to give it a try. 
It is not functional yet as I have to patch registermapping.

**Comment by RobTillaart** [comment]
A few hours of focus ==> https://github.com/RobTillaart/PCA9634  
If you have time please verify if it works and /or errors you encounter.

----
update:
The build / unit test has some minor failures like lint but work is in progress.
library itself compiles and could work as intended.

**Comment by Luxovious** [comment]
I "answered" with a few comments (nothing special) your new repository.
You did an amazing job!
