### ISSUE TITLE
ESP32 + PCA9635 Flash at boot

### ISSUE THREAD

**Issue by jonascant** [RobTillaart/PCA9635#20]
Hi, is it possible to avoid the brief flash at Boot? Perhaps utilizing the OE Pin?
Thanks!

**Comment by RobTillaart** [comment]
Can you explain a bit more?

**Comment by jonascant** [comment]
Sorry,
Whenever i connect power to the SOC, all channels on the PCA9635 seem to be at the maximum output value, causing a flash on the connected LEDs. When my arduino sketch has loaded, everything is like it should be. Just this brief flash at boot time causes me trouble.

I experienced this with the ESP32 (lolin d32 pro) and ESP8266 (wemos d1 mini).

**Comment by RobTillaart** [comment]
I have to look into this, might take a few days. has been quite some time that I worked actually with the library.

**Comment by jonascant** [comment]
Thank you. This is one of the circuits i am using:
![2023-01-23-172434_649x567_scrot](https://user-images.githubusercontent.com/46350140/214094058-685eecda-a90d-4770-8260-cbde67284f61.png)

**Comment by jonascant** [comment]
R2 and R3 are not connected. This is to be able to use two transistors without the PCA chip if needed.

**Comment by RobTillaart** [comment]
From datasheet

![image](https://user-images.githubusercontent.com/462844/214095000-7bd1d77a-84a8-4d9f-888b-d476c10d6e55.png)

So it will cost an IO pin + pull up resistor 1 - 10 K or so to be sure OE is HIGH at startup.

**Comment by RobTillaart** [comment]
I'm thinking of this interface

1. there should be a function to define the OE pin       **setOutputEnablePin(uint8_t pin)**
2. there should be a function to set OE pin HIGH   **setOutputEnable(uint8_t value)** LOW HIGH
3. there should be a function to set OE pin LOW.   **setOutputEnable(uint8_t value)** LOW HIGH

The latter could also be 2 functions, but as it is expected not being used often, a single one saves some RAM.

Does this meet your needs?

I will prepare a develop branch for it as I think it is a nice feature.

**Comment by RobTillaart** [comment]
Created a develop branch https://github.com/RobTillaart/PCA9635/tree/develop

Three functions

- **bool setOutputEnablePin(uint8_t pin = 255)** sets the IO pin to connect to the OE pin of the PCA9635.
A value of 255 indicates no pin set/selected.
Returns true on success.
- **bool enableOutput(uint8_t value)** Sets the OE pin HIGH or LOW.
All non zero values are HIGH.
Returns true on success.
- **uint8_t getOutputEnable()** get the current value of the OE pin.
If pin is not set/selected it will return LOW.


Give it a try

**Comment by RobTillaart** [comment]
@jonascant 
Did you have time to try the develop branch?

**Comment by jonascant** [comment]
Thank you! I didn't get around to it yet, but I will until tomorrow night!

**Comment by RobTillaart** [comment]
@jonascant 
Any progress?

**Comment by RobTillaart** [comment]
@jonascant
Any progress?

**Comment by jonascant** [comment]
Truly sorry, my life got a little crazy. I will test it. Thanks so much! Jonas

Am 20. Februar 2023 17:32:34 MEZ schrieb Rob Tillaart ***@***.***>:

**Comment by RobTillaart** [comment]
Don't feel pushed, it was silent for quite some time so I was wondering.

**Comment by RobTillaart** [comment]
@jonascant
Any progress?

**Comment by RobTillaart** [comment]
@jonascant
I decided to merge the PR
- code is pretty straightforward
- I did not find problems 
- the issue is open for more than a month

If you have test results later I am happy to hear your experiences.

**Comment by jonascant** [comment]
Thank you, I will let you know! Thanks again!

Am 7. März 2023 16:16:19 MEZ schrieb Rob Tillaart ***@***.***>:
