### ISSUE TITLE
setLedDriverMode(uint8_t mode) doesn't set LedDriverMode for all channels

### ISSUE THREAD

**Issue by khangtranduc** [RobTillaart/PCA9635#32]
Only channels 0-11 are set to the desired mode using this method, with channels 12-15 not being set to desired mode.
Manual setting using setLedDriverMode(uint8_t channel, uint8_t mode) for every channel (from 0 through 15) works though.

**Comment by RobTillaart** [comment]
Thanks for reporting this issue.
I will look into it asap however it might take a few days.

**Comment by RobTillaart** [comment]
Quick look at the code and found a possible cause.

Can you change line 520 in the .cpp file?
Change 3 to 4 in the for loop so it becomes:
```cpp
for (int reg = 0; reg < 4; reg++)
  {
    writeLedOut(reg, mask);
  }
```
Please let me know if that fixes the issue.

**Comment by khangtranduc** [comment]
Wow, thank you for the prompt response! I will try that later once I'm back.

**Comment by khangtranduc** [comment]
Yes it works!

**Comment by RobTillaart** [comment]
new version 0.6.0 released with fix.
